### ISSUE TITLE
duplicationType encoded as JSON Object, but attempted to parse as JSON Array

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-store#175] opened 2017-01-11 01:48 UTC
Stack trace seems to show an attribute being attempted to be parsed as a JSON Array (to a String[]), but the debugging appears to show the value as an Object, which should be parsed to Map&lt;String, Object&gt;

```
2017-01-11 06:12:16,060 ERROR: [POSO] - Problem de-serialising value: duplicationType : {"empty":false,"traversableAgain":true} - Can not deserialize instance of java.lang.String[] out of START_OBJECT token
 at [Source: java.io.StringReader@2cdea607; line: 1, column: 1]
org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String[] out of START_OBJECT token
 at [Source: java.io.StringReader@2cdea607; line: 1, column: 1]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219)
	at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:212)
	at org.codehaus.jackson.map.deser.std.PrimitiveArrayDeserializers$StringDeser.handleNonArray(PrimitiveArrayDeserializers.java:153)
	at org.codehaus.jackson.map.deser.std.PrimitiveArrayDeserializers$StringDeser.deserialize(PrimitiveArrayDeserializers.java:119)
	at org.codehaus.jackson.map.deser.std.PrimitiveArrayDeserializers$StringDeser.deserialize(PrimitiveArrayDeserializers.java:107)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at au.org.ala.biocache.util.Json$.toArray(Json.scala:91)
	at au.org.ala.biocache.poso.POSO$class.setProperty(POSO.scala:62)
	at au.org.ala.biocache.model.Occurrence.setProperty(Occurrence.scala:11)
	at au.org.ala.biocache.poso.CompositePOSO$class.setNestedProperty(CompositePOSO.scala:123)
	at au.org.ala.biocache.model.FullRecord.setNestedProperty(FullRecord.scala:15)
	at au.org.ala.biocache.poso.CompositePOSO$class.setProperty(CompositePOSO.scala:97)
	at au.org.ala.biocache.model.FullRecord.setProperty(FullRecord.scala:15)
	at au.org.ala.biocache.load.FullRecordMapper$$anonfun$createFullRecord$4.apply(FullRecordMapper.scala:189)
	at au.org.ala.biocache.load.FullRecordMapper$$anonfun$createFullRecord$4.apply(FullRecordMapper.scala:145)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
	at au.org.ala.biocache.load.FullRecordMapper$.createFullRecord(FullRecordMapper.scala:145)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:420)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl$$anonfun$pageOverRawProcessed$1.apply(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:344)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager$$anonfun$pageOver$1.apply(CassandraPersistenceManager.scala:336)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOver(CassandraPersistenceManager.scala:336)
	at au.org.ala.biocache.persistence.CassandraPersistenceManager.pageOverAll(CassandraPersistenceManager.scala:482)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.pageOverRawProcessed(OccurrenceDAOImpl.scala:417)
	at au.org.ala.biocache.index.ProcessRecordsRunner.run(IndexRecordMultiThreaded.scala:392)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by djtfmartin** [comment] 2018-04-24 14:12
this looks like a scala-jackson JSON serialisation issue. closing because there isnt a record GUID to test against (difficult to reproduce).

**Closed by djtfmartin** 2018-04-24 14:12 UTC

**Comment by ansell** [comment] 2018-04-25 20:40
Definitely going to be difficult to reproduce over 12 months after it being reported. 

The core reason is that the code attempts to deserialise cassandra records into ``Occurrence`` objects, which persists the ``classs`` issue that it creates from Scala/Java down into Cassandra and from there into other data quality methods, making it more difficult to work with either biocache-store or Cassandra for data verification.
