### ISSUE TITLE
ingest process for Darwin Core archive including multiple images

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#29] opened 2015-01-20 03:50 UTC
_From @mbohun on August 19, 2014 12:33_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=526
*date:* Wed Jan 15 16:14:34 2014
*author:* milo_nic...@hotmail.com
 ---

Both MV and AM have requested to include multiple images with distinct metadata (e.g. photographer, rights).  We have recommended they produce a Darwin Core archive using the simple image extension [http://rs.gbif.org/extension/gbif/1.0/images.xml](http://rs.gbif.org/extension/gbif/1.0/images.xml).  The ingest process needs to be developed for the DWC-A.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#56_

**Comment by nickdos** [comment] 2015-01-20 03:50
_From @mbohun on August 19, 2014 12:33_


*date:* Wed Apr 30 23:38:49 2014
*author:* natasha....@csiro.au
 ---

This also relates to supporting a DWCA Star schema. AVH is delivery identification history as a star archive and at the moment we have been ignoring them.

After we have this fix in the system someone will need to let Niels know that he should resend all the records that have an identification history.

**Comment by nickdos** [comment] 2015-01-20 03:50
_From @mbohun on August 19, 2014 12:33_


*date:* Thu May  1 21:35:24 2014
*author:* natasha....@csiro.au
 ---

Comment above describes status

 ---
**UPDATES:**
*Owner:* moyesyside

**Comment by djtfmartin** [comment] 2015-05-18 15:58
duplicate of https://github.com/AtlasOfLivingAustralia/biocache-store/issues/48

**Closed by djtfmartin** 2015-05-18 15:58 UTC
Labels: enhancement, priority-medium, status-new, type-defect
